FROM ubuntu:14.04

RUN echo 'deb http://us.archive.ubuntu.com/ubuntu/ precise universe' >> /etc/apt/sources.list
RUN apt-get -y update
RUN apt-get -y install python python-pip build-essential
RUN pip install flask flask-sqlalchemy
RUN apt-get -y purge build-essential
RUN apt-get -y autoremove

RUN flask --app=flaskr initdb

CMD ["flask", "--app=flaskr", "run"]